### ISSUE TITLE
Using Crafts svg filter in Fractal

### ISSUE THREAD

**Issue by john-henry** [madebyraygun/craft-fractal#6]
Hi Dalton,

I get that Fractal is using Twig JS. 
I wanted to use [SVG filter ](https://craftcms.com/docs/4.x/dev/functions.html#svg) from Craft 

I saw some work in fractal for filters and functions, specifically typogrify. Were they just pseudo-placeholders so Fractal doesn't complain when rendered?

**Comment by daltonrooney** [comment]
@john-henry You're right, for any Craft-specific Twig filters and functions we need to use, we mock them up in Fractal so they won't cause an error. Those are in https://github.com/madebyraygun/craft-fractal/blob/dev/fractal/config/filters.js and https://github.com/madebyraygun/craft-fractal/blob/dev/fractal/config/functions.js

But we generally try to avoid using Craft-specific filters and functions if we can, to keep the front-end as agnostic as possible. For example, the Typogrify plugin has a service that you can call from your PHP modules, so we aren't using that filter in Twig anymore.

You can see how we handle SVGs in [EntryUtils.php](https://github.com/madebyraygun/craft-fractal/blob/19a044e604e6470c1c9878b8b9487df2d2acfc2a/craft/modules/common/EntryUtils.php#L25C1-L31C1)

```
use craft\helpers\Html;

class EntryUtils extends Module {
  ...
  public static function SvgContents($queryImage) {
    $icon = self::QueryOne($queryImage);
    $svg = $icon && $icon->extension == 'svg' ? $icon->getContents() : null;
    return $svg ? Html::sanitizeSvg($svg) : null;
  }
  ...
}
```

Then you can call that from another context module like so:

```
  public static function getLogo($context) {
    $app = $context['craft']->app;
    $globals = $app->getGlobals()->getSetByHandle('masthead');
    return [
      'url' => UrlHelper::siteUrl('/'),
      'title' => Craft::$app->sites->currentSite->name,
      'svg' => EntryUtils::SvgContents($globals->siteLogo);
    ];
  }
```

And then our `logo.twig` file looks something like this:

```
<div class="site-logo">
  {% if url|default %}
    <a href="{{url}}">
  {% endif %}
  {% if svg|default %}
    {{ svg|raw }}
  {% endif %}
  <span class="is-sr-only">{{title}}</span>
  {% if url|default %}
    </a>
  {% endif %}
</div>
```

The output should be similar to the output of the Craft SVG function.

**Comment by john-henry** [comment]
Great answer thanks!
